apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: NAMESPACE_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter-app
        image: 886047841413.dkr.ecr.us-east-2.amazonaws.com/my-app-repo:v2
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: NAMESPACE_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
